import { vinicuncaESLint } from '@vinicunca/eslint-config';

export default vinicuncaESLint(
  {
    formatters: {
      html: true,
    },
    typescript: true,
    unocss: {
      configPath: './apps/web/uno.config.ts',
    },
    vue: true,
  },

  {
    // @taman/emails build output: Maizzle's HTML/text build dirs and the
    // committed codegen modules (regenerated by `build:templates`).
    ignores: [
      'packages/server/emails/.cache/**',
      'packages/server/emails/.maizzle/**',
      'packages/server/emails/src/generated/**',
    ],
  },

  {
    rules: {
      'pnpm/yaml-enforce-settings': 'off',

      // Workspace packages form their own group after external imports, so
      // import order does not depend on the scope name (`create-taman`
      // renames `@taman/` to the project's scope).
      'perfectionist/sort-imports': [
        'error',
        {
          groups: [
            'type-import',
            ['type-parent', 'type-sibling', 'type-index', 'type-internal'],
            'value-builtin',
            'value-external',
            'value-internal',
            ['value-parent', 'value-sibling', 'value-index'],
            'side-effect',
            'ts-equals-import',
            'unknown',
          ],
          internalPattern: ['^~/.+', '^@/.+', '^@taman/'],
          newlinesBetween: 'ignore',
          order: 'asc',
          type: 'natural',
        },
      ],

      'unocss/order': [
        'warn',
        {
          unoVariables: ['^theme'],
        },
      ],
    },
  },

  {
    files: [
      '**/scripts/**',
      '**/db/**',
      '**/db-pg/**',
      '**/playwright.config.ts',
      '**/internal/**/*.ts',
      './apps/**/server/**/*.ts',
    ],
    rules: {
      'node/prefer-global/process': 'off',
    },
  },

  {
    files: [
      '**/e2e/**',
    ],
    rules: {
      'sonar/assertions-in-tests': 'off',
    },
  },
);
