/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PApp: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/App.vue')['default']
    PAuthForm: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/AuthForm.vue')['default']
    PAvatar: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Avatar.vue')['default']
    PBreadcrumb: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Breadcrumb.vue')['default']
    PButton: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Button.vue')['default']
    PCard: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.6_94729d8e300bd9608d7a36eb938da2cc/node_modules/pohon-ui/dist/runtime/components/Card.vue')['default']
    PCommandPalette: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_94729d8e300bd9608d7a36eb938da2cc/node_modules/pohon-ui/dist/runtime/components/CommandPalette.vue')['default']
    PContextMenu: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/ContextMenu.vue')['default']
    PDropdownMenu: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/DropdownMenu.vue')['default']
    PFileUpload: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/FileUpload.vue')['default']
    PForm: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Form.vue')['default']
    PFormField: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/FormField.vue')['default']
    PIcon: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/vue/components/Icon.vue')['default']
    PInput: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Input.vue')['default']
    PKbd: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Kbd.vue')['default']
    PModal: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Modal.vue')['default']
    PPopover: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Popover.vue')['default']
    PSeparator: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Separator.vue')['default']
    PSlider: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.3_c08bbda8172004bd52f76e9b55f9c5df/node_modules/pohon-ui/dist/runtime/components/Slider.vue')['default']
    PSwitch: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Switch.vue')['default']
    PTabs: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Tabs.vue')['default']
    PTooltip: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Tooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const PApp: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/App.vue')['default']
  const PAuthForm: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/AuthForm.vue')['default']
  const PAvatar: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Avatar.vue')['default']
  const PBreadcrumb: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Breadcrumb.vue')['default']
  const PButton: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Button.vue')['default']
  const PCard: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.6_94729d8e300bd9608d7a36eb938da2cc/node_modules/pohon-ui/dist/runtime/components/Card.vue')['default']
  const PCommandPalette: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_94729d8e300bd9608d7a36eb938da2cc/node_modules/pohon-ui/dist/runtime/components/CommandPalette.vue')['default']
  const PContextMenu: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/ContextMenu.vue')['default']
  const PDropdownMenu: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/DropdownMenu.vue')['default']
  const PFileUpload: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/FileUpload.vue')['default']
  const PForm: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Form.vue')['default']
  const PFormField: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/FormField.vue')['default']
  const PIcon: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/vue/components/Icon.vue')['default']
  const PInput: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Input.vue')['default']
  const PKbd: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Kbd.vue')['default']
  const PModal: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Modal.vue')['default']
  const PPopover: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Popover.vue')['default']
  const PSeparator: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Separator.vue')['default']
  const PSlider: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.3_c08bbda8172004bd52f76e9b55f9c5df/node_modules/pohon-ui/dist/runtime/components/Slider.vue')['default']
  const PSwitch: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Switch.vue')['default']
  const PTabs: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_bcb3767dc29a07de0b758b3ed4f69159/node_modules/pohon-ui/dist/runtime/components/Tabs.vue')['default']
  const PTooltip: typeof import('./../../node_modules/.pnpm/pohon-ui@2.0.0-rc7.7_53fc48d05091592f8da2bfc9d5e8698a/node_modules/pohon-ui/dist/runtime/components/Tooltip.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}