import type { Preferences } from './types';

const defaultPreferences: Preferences = {
  app: {
    accessMode: 'frontend',
    authPageLayout: 'panel-right',
    checkUpdatesInterval: 1,
    colorGrayMode: false,
    colorWeakMode: false,
    compact: false,
    contentCompact: 'wide',
    contentCompactWidth: 1200,
    contentPadding: 0,
    contentPaddingBottom: 0,
    contentPaddingLeft: 0,
    contentPaddingRight: 0,
    contentPaddingTop: 0,
    defaultAvatar:
      'https://unpkg.com/@vbenjs/static-source@0.1.7/source/avatar-v1.webp',
    defaultHomePath: '/dashboard',
    dynamicTitle: true,
    enableCheckUpdates: true,
    enableCopyPreferences: true,
    enablePreferences: true,
    enableRefreshToken: false,
    enableStickyPreferencesNavigationBar: true,
    isMobile: false,
    layout: 'sidebar-nav',
    locale: 'en-US',
    loginExpiredMode: 'page',
    name: 'Taman Admin',
    preferencesButtonPosition: 'auto',
    timezone: 'Asia/Shanghai',
    watermark: false,
    watermarkContent: '',
    zIndex: 200,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: false,
    showIcon: true,
  },
  copyright: {
    companyName: 'Taman',
    companySiteLink: 'https://www.taman.com',
    date: '2026',
    enable: true,
    settingShow: true,
  },
  footer: {
    enable: false,
    fixed: false,
    height: 32,
  },
  header: {
    enable: true,
    height: 50,
    hidden: false,
    menuAlign: 'start',
    mode: 'fixed',
  },

  logo: {
    enable: true,
    fit: 'contain',
    source: 'https://assets.ngibur.com/global/core-logo.webp',
  },
  navigation: {
    accordion: true,
    split: true,
    styleType: 'rounded',
  },
  shortcutKeys: {
    enable: true,
    globalLockScreen: true,
    globalLogout: true,
    globalPreferences: true,
    globalSearch: true,
  },
  sidebar: {
    autoActivateChild: false,
    collapsed: false,
    collapsedButton: true,
    collapsedShowTitle: false,
    collapseWidth: 60,
    draggable: true,
    enable: true,
    expandOnHover: true,
    extraCollapse: false,
    extraCollapsedWidth: 60,
    fixedButton: true,
    hidden: false,
    mixedWidth: 80,
    width: 224,
  },
  tabbar: {
    draggable: true,
    enable: true,
    height: 38,
    keepAlive: true,
    maxCount: 0,
    middleClickToClose: false,
    persist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    showRefresh: true,
    styleType: 'chrome',
    visitHistory: true,
    wheelable: true,
  },
  theme: {
    builtinType: 'default',
    brands: {
      error: 'hsl(348 100% 61%)',
      primary: 'hsl(212 100% 45%)',
      success: 'hsl(144 57% 58%)',
      warning: 'hsl(42 84% 61%)',
    },
    radius: '0.5',
    fontSize: 16,
    semiDarkHeader: false,
    semiDarkSidebar: false,
    semiDarkSidebarSub: false,
  },
  transition: {
    enable: true,
    loading: true,
    name: 'fade-slide',
    progress: true,
  },
  widget: {
    fullscreen: true,
    fullscreenButtonPosition: 'header',
    globalSearch: true,
    globalSearchButtonPosition: 'header',
    languageToggle: true,
    languageToggleButtonPosition: 'header',
    lockScreen: true,
    lockScreenButtonPosition: 'header',
    logoutButtonPosition: 'header',
    notification: true,
    notificationButtonPosition: 'header',
    refresh: true,
    refreshButtonPosition: 'header',
    sidebarToggle: true,
    themeToggle: true,
    themeToggleButtonPosition: 'header',
    timezone: true,
    timezoneButtonPosition: 'header',
    order: [
      'globalSearch',
      'preferences',
      'themeToggle',
      'languageToggle',
      'timezone',
      'fullscreen',
      'refresh',
      'notification',
      'lockScreenButton',
      'logoutButton',
    ],
  },
};

export { defaultPreferences };
