import type { Preferences } from './types';
import {
  TAMAN_ACCESS_MODE_TYPE,
  TAMAN_AUTH_PAGE_LAYOUT_TYPE,
  TAMAN_BREADCRUMB_STYLE_TYPE,
  TAMAN_CONTENT_COMPACT_TYPE,
  TAMAN_LAYOUT_HEADER_MENU_ALIGN_TYPE,
  TAMAN_LAYOUT_HEADER_MODE_TYPE,
  TAMAN_LAYOUT_TYPE,
  TAMAN_LOGIN_EXPIRED_MODE_TYPE,
  TAMAN_NAVIGATION_STYLE_TYPE,
  TAMAN_PAGE_TRANSITION_TYPE,
  TAMAN_PREFERENCES_BUTTON_POSITION_TYPE,
  TAMAN_TABS_STYLE_TYPE,
  TAMAN_THEME_MODE_TYPE,
} from '@taman-core/typings';

const defaultPreferences: Preferences = {
  app: {
    accessMode: TAMAN_ACCESS_MODE_TYPE.FRONTEND,
    authPageLayout: TAMAN_AUTH_PAGE_LAYOUT_TYPE.PANEL_RIGHT,
    checkUpdatesInterval: 1,
    colorGrayMode: false,
    colorWeakMode: false,
    compact: false,
    contentCompact: TAMAN_CONTENT_COMPACT_TYPE.WIDE,
    contentCompactWidth: 1200,
    contentPadding: 0,
    contentPaddingBottom: 0,
    contentPaddingLeft: 0,
    contentPaddingRight: 0,
    contentPaddingTop: 0,
    defaultAvatar: '',
    defaultHomePath: '/analytics',
    dynamicTitle: true,
    enableCheckUpdates: true,
    enableCopyPreferences: true,
    enablePreferences: true,
    enableRefreshToken: false,
    enableStickyPreferencesNavigationBar: true,
    isMobile: false,
    layout: TAMAN_LAYOUT_TYPE.SIDEBAR_NAV,
    locale: 'en-US',
    loginExpiredMode: TAMAN_LOGIN_EXPIRED_MODE_TYPE.PAGE,
    name: 'Taman Admin',
    preferencesButtonPosition: TAMAN_PREFERENCES_BUTTON_POSITION_TYPE.AUTO,
    timezone: 'Asia/Shanghai',
    watermark: false,
    watermarkContent: '',
    zIndex: 200,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: false,
    showIcon: true,
    styleType: TAMAN_BREADCRUMB_STYLE_TYPE.NORMAL,
  },
  copyright: {
    companyName: 'Taman',
    companySiteLink: 'https://taman.vinicunca.dev',
    date: '2024',
    enable: true,
    icp: '',
    icpLink: '',
    settingShow: true,
  },
  footer: {
    enable: false,
    fixed: false,
    height: 32,
  },
  header: {
    enable: true,
    height: 50,
    hidden: false,
    menuAlign: TAMAN_LAYOUT_HEADER_MENU_ALIGN_TYPE.START,
    mode: TAMAN_LAYOUT_HEADER_MODE_TYPE.FIXED,
  },
  logo: {
    enable: true,
    fit: 'contain',
    source: 'https://taman.vinicunca.dev/logo.svg',
  },
  navigation: {
    accordion: true,
    split: true,
    styleType: TAMAN_NAVIGATION_STYLE_TYPE.ROUNDED,
  },
  shortcutKeys: {
    enable: true,
    globalEscape: false,
    globalLockScreen: true,
    globalLogout: true,
    globalPreferences: true,
    globalSearch: true,
  },
  sidebar: {
    autoActivateChild: false,
    collapsed: false,
    collapsedButton: true,
    collapsedShowTitle: false,
    collapseWidth: 60,
    draggable: true,
    enable: true,
    expandOnHover: true,
    extraCollapse: false,
    extraCollapsedWidth: 60,
    fixedButton: true,
    hidden: false,
    mixedWidth: 80,
    width: 224,
  },
  tabbar: {
    draggable: true,
    enable: true,
    height: 38,
    keepAlive: true,
    maxCount: 0,
    middleClickToClose: false,
    persist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    showRefresh: true,
    styleType: TAMAN_TABS_STYLE_TYPE.CHROME,
    visitHistory: true,
    wheelable: true,
  },
  theme: {
    builtinType: 'default',
    colorDestructive: 'hsl(348 100% 61%)',
    colorPrimary: 'hsl(212 100% 45%)',
    colorSuccess: 'hsl(144 57% 58%)',
    colorWarning: 'hsl(42 84% 61%)',
    mode: TAMAN_THEME_MODE_TYPE.DARK,
    radius: '0.5',
    fontSize: 16,
    semiDarkHeader: false,
    semiDarkSidebar: false,
    semiDarkSidebarSub: false,
  },
  transition: {
    enable: true,
    loading: true,
    name: TAMAN_PAGE_TRANSITION_TYPE.FADE_SLIDE,
    progress: true,
  },
  widget: {
    fullscreen: true,
    globalSearch: true,
    languageToggle: true,
    lockScreen: true,
    notification: true,
    refresh: true,
    sidebarToggle: true,
    themeToggle: true,
    timezone: true,
  },
};

export { defaultPreferences };
