// @unocss-include
import type { PThemeCommandPalette } from 'pohon-ui';

export const themeCommandPalette = {
  slots: {
    root: 'divide-divide flex flex-col min-h-0 min-w-0 divide-y',
    input: '',
    close: '',
    back: 'p-0',
    content: 'flex flex-col relative overflow-hidden',
    footer: 'p-1',
    viewport: 'flex-1 relative overflow-y-auto scroll-py-1 focus:outline-none',
    group: 'p-1 isolate',
    empty: 'color-text-muted text-center',
    label: 'color-text-highlighted font-600',
    item: 'group outline-none flex w-full select-none items-start relative before:(rounded-md content-empty inset-px absolute -z-1) data-[disabled]:(opacity-75 cursor-not-allowed)',
    itemLeadingIcon: 'shrink-0',
    itemLeadingAvatar: 'shrink-0',
    itemLeadingAvatarSize: '',
    itemLeadingChip: 'shrink-0',
    itemLeadingChipSize: '',
    itemTrailing: 'ms-auto inline-flex items-center',
    itemTrailingIcon: 'shrink-0',
    itemTrailingHighlightedIcon: 'color-text-dimmed shrink-0 hidden group-data-[highlighted]:inline-flex',
    itemTrailingKbds: 'shrink-0 hidden items-center lg:inline-flex',
    itemTrailingKbdsSize: '',
    itemWrapper: 'text-start flex flex-1 flex-col min-w-0',
    itemLabel: 'color-text-dimmed truncate space-x-1',
    itemLabelBase: 'color-text-highlighted [&>mark]:color-primary [&>mark]:bg-primary/15',
    itemLabelPrefix: 'color-text',
    itemLabelSuffix: 'color-text-dimmed [&>mark]:color-primary [&>mark]:bg-primary/15',
    itemDescription: 'color-text-muted [&>mark]:color-primary [&>mark]:bg-primary/15 truncate',
  },
  variants: {
    virtualize: {
      true: {
        viewport: 'p-1 isolate',
      },
      false: {
        viewport: 'divide-divide divide-y',
      },
    },
    size: {
      xs: {
        input: '[&>input]:h-10',
        empty: 'text-xs py-3',
        label: 'text-[10px]/3 p-1 gap-1',
        item: 'text-xs p-1 gap-1',
        itemLeadingIcon: 'size-4',
        itemLeadingAvatarSize: '3xs',
        itemLeadingChip: 'size-4',
        itemLeadingChipSize: 'sm',
        itemTrailing: 'gap-1',
        itemTrailingIcon: 'size-4',
        itemTrailingHighlightedIcon: 'size-4',
        itemTrailingKbds: 'gap-0.5',
        itemTrailingKbdsSize: 'sm',
      },
      sm: {
        input: '[&>input]:h-11',
        empty: 'text-xs py-4',
        label: 'text-[10px]/3 p-1.5 gap-1.5',
        item: 'text-xs p-1.5 gap-1.5',
        itemLeadingIcon: 'size-4',
        itemLeadingAvatarSize: '3xs',
        itemLeadingChip: 'size-4',
        itemLeadingChipSize: 'sm',
        itemTrailing: 'gap-1.5',
        itemTrailingIcon: 'size-4',
        itemTrailingHighlightedIcon: 'size-4',
        itemTrailingKbds: 'gap-0.5',
        itemTrailingKbdsSize: 'sm',
      },
      md: {
        input: '[&>input]:h-12',
        empty: 'text-sm py-6',
        label: 'text-xs p-1.5 gap-1.5',
        item: 'text-sm p-1.5 gap-1.5',
        itemLeadingIcon: 'size-5',
        itemLeadingAvatarSize: '2xs',
        itemLeadingChip: 'size-5',
        itemLeadingChipSize: 'md',
        itemTrailing: 'gap-1.5',
        itemTrailingIcon: 'size-5',
        itemTrailingHighlightedIcon: 'size-5',
        itemTrailingKbds: 'gap-0.5',
        itemTrailingKbdsSize: 'md',
      },
      lg: {
        input: '[&>input]:h-13',
        empty: 'text-sm py-7',
        label: 'text-xs p-2 gap-2',
        item: 'text-sm p-2 gap-2',
        itemLeadingIcon: 'size-5',
        itemLeadingAvatarSize: '2xs',
        itemLeadingChip: 'size-5',
        itemLeadingChipSize: 'md',
        itemTrailing: 'gap-2',
        itemTrailingIcon: 'size-5',
        itemTrailingHighlightedIcon: 'size-5',
        itemTrailingKbds: 'gap-0.5',
        itemTrailingKbdsSize: 'md',
      },
      xl: {
        input: '[&>input]:h-14',
        empty: 'text-base py-8',
        label: 'text-sm p-2 gap-2',
        item: 'text-base p-2 gap-2',
        itemLeadingIcon: 'size-6',
        itemLeadingAvatarSize: 'xs',
        itemLeadingChip: 'size-6',
        itemLeadingChipSize: 'lg',
        itemTrailing: 'gap-2',
        itemTrailingIcon: 'size-6',
        itemTrailingHighlightedIcon: 'size-6',
        itemTrailingKbds: 'gap-0.5',
        itemTrailingKbdsSize: 'lg',
      },
    },
    active: {
      true: {
        item: 'color-text-highlighted before:bg-background-elevated',
        itemLeadingIcon: 'color-text',
      },
      false: {
        item: 'color-text data-[highlighted]:not-[[data-disabled]]:color-text-highlighted data-[highlighted]:not-[[data-disabled]]:before:bg-background-elevated/50 transition-colors before:transition-colors',
        itemLeadingIcon: 'color-text-dimmed [.group[data-highlighted]:not([data-disabled])_&]:color-text transition-colors',
      },
    },
    loading: {
      true: {
        itemLeadingIcon: 'animate-spin',
      },
    },
  },
} satisfies PThemeCommandPalette;
